import { Geist, Geist_Mono, Plus_Jakarta_Sans, Syne, Anton } from "next/font/google";
import "./globals.css";
import Nav from "@/shared/Nav";
import Footer from "@/shared/Footer";
import UpToDate from "@/components/Home/UpToDate";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"]
})

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"]
})


const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const header = await headers()
  const currentPath = header.get('referer') || '';

  console.log(currentPath);


  const adminRoute = String(currentPath).includes("admin")
  console.log(adminRoute);



  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} ${jakartaSans.variable} ${syne.variable} ${anton.variable} h-full antialiased`}
    >
     
      {
        !adminRoute &&  <Nav />
      }
      <body className="min-h-full flex flex-col">{children}</body>
      {
        !adminRoute && <> <UpToDate />
          <Footer /></>
      }
    </html>
  );
}
